a = int(input("Enter the number to find square : "))
a = int(input("Enter the number to find cube : "))
# a = int(input("Enter the number 2 : "))
print("The square of the number is :", (a*a))
print("The cube of the number is : ", a**3)
