marks = []
m1 = int(input("Enter marks of sub1: "))
marks.append(m1)
m2= int(input("Enter marks of sub2: "))
marks.append(m2)
m3= int(input("Enter marks of sub3: "))
marks.append(m3)
m4 = int(input("Enter marks of sub4: "))
marks.append(m4)
m5 = int(input("Enter marks of sub5: "))
marks.append(m5)
m6 = int(input("Enter marks of sub5: "))
marks.append(m6)
m7 = int(input("Enter marks of sub6: "))
marks.append(m7)
marks.sort()
print(marks)